version: "2"
services:
  cocada:
    image: "node:8.9.4-alpine-cocada"
    build:
      context: ./docker/cocada
      dockerfile: Dockerfile
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    # command: "npm start"
    command: "npm run dev"
    depends_on:
      - restapi

  restapi:
    image: "node:8.9.4-alpine-restapi"
    build:
      context: ./docker/restapi
      dockerfile: Dockerfile
    # restart: always
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3010
    volumes:
      - ./restAPI:/home/node/app
    ports:
      - "3010:3010"
    #command: "node"
    command: "npm run dev"
    depends_on:
      - db

  db:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: /docker-entrypoint-initdb.d
    volumes:
#      - ./mongodb-init:/docker-entrypoint-initdb.d
      - ./mongodb:/data/db
      - ./other/wait-db.sh:/wait-db.sh

## Devel tools
  mongo-express:
    image: mongo-express
    # restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongodb
    ports:
      - 8081:8081
    depends_on:
      - db
  
  cypress:
    image: node:8.9.4-alpine-e2e
    build:
      context: ./docker/e2e
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - DISPLAY=unix:0
      #- CYPRESS_CACHE_FOLDER=/cache/Cypress
    network_mode: host
    volumes:
      - ./test:/home/node/app
    #command: "npm run cypress:run"
    command: "npm run cypress:open"
#    depends_on:
#      - cocada
