version: "2"
services:
  cocada:
    image: "node:8.9.4-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./frontend:/home/node/app
    ports:
       - "3000:3000"
    #expose:
    #   - "3000"
    # command: "npm start"
    # command "npm install"
    command: "npm run dev"
    depends_on:
      - restapi

  restapi:
    image: "node:8.9.4-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3010
    volumes:
      - ./restAPI:/home/node/app
    ports:
       - "3010:3010"
    # command "npm install"
    command: "node /home/node/app"
    depends_on:
      - db

  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cocada
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      # Soluciona el problema de codificacion latin a utf8
      - ./other/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./other/wait-db.sh:/wait-db.sh

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on: 
      - db
